import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title> Next Email App </title>
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main
          style={{
            flex: 1,
            overflowY: "auto",
            maxHeight: "calc(100vh - 84px)",
          }}
        >
          {children}
        </main>{" "}
        <Footer />
      </body>
    </html>
  );
}
